FROM oven/bun:1
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --ignore-scripts

COPY prisma ./prisma
COPY prisma.config.ts .
RUN bunx prisma generate

CMD ["bunx", "prisma", "studio", "--port", "5555", "--browser", "none"]
